//import './globals.css'
'use client'

import Link from 'next/link'
import { Layout, Nav, Button, Breadcrumb, Skeleton, Avatar } from '@douyinfe/semi-ui';
import { IconSemiLogo, IconBell, IconHelpCircle, IconBytedanceLogo, IconStar, IconUser, IconUserGroup, IconSetting } from '@douyinfe/semi-icons';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useRouter, } from 'next/navigation'
import React, { useState, useMemo } from 'react';

const inter = Inter({ subsets: ['latin'] })
/*
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { Header, Footer, Sider, Content } = Layout;
  const router = useRouter();
  const scroll = useMemo(() => ({ y: 300, x: 1200 }), []);
  return (
    <html lang="en">
      <head></head>
      <body>
        <Layout style={{ border: '1px solid var(--semi-color-border)'}}>
          <Header style={{ backgroundColor: 'var(--semi-color-bg-1)' }}>
            <div>
              <Nav mode="horizontal" defaultSelectedKeys={['Home']}>
                <Nav.Header>
                  <IconSemiLogo style={{ height: '36px', fontSize: 36 }} />
                </Nav.Header>
                <span
                  style={{
                    color: 'var(--semi-color-text-2)',
                  }}
                >
                  <span
                    style={{
                      marginRight: '24px',
                      color: 'var(--semi-color-text-0)',
                      fontWeight: '600',
                    }}
                  >
                    模版推荐
                  </span>
                  <span style={{ marginRight: '24px' }}>所有模版</span>
                  <span>我的模版</span>
                </span>
                <Nav.Footer>
                  <Button
                    theme="borderless"
                    icon={<IconBell size="large" />}
                    style={{
                      color: 'var(--semi-color-text-2)',
                      marginRight: '12px',
                    }}
                  />
                  <Button
                    theme="borderless"
                    icon={<IconHelpCircle size="large" />}
                    style={{
                      color: 'var(--semi-color-text-2)',
                      marginRight: '12px',
                    }}
                  />
                  <Avatar color="orange" size="small">
                    YJ
                  </Avatar>
                </Nav.Footer>
              </Nav>
            </div>
          </Header>
          <Layout>
            <Sider style={{ backgroundColor: 'var(--semi-color-bg-1)' }}>
              <Nav
                bodyStyle={{ height: "640px" }}
                defaultOpenKeys={['user', 'union']}
                onSelect={data => console.log('trigger onSelect: ', data)}
                onClick={data => {
                  console.log('trigger onClick: ', data);
                  switch (data.itemKey) {
                    case "grids":
                      router.push('/semi/grids');
                      break;
                    case "forms":
                      router.push('/semi/forms');
                      break;

                  }

                }}
              >
                <Nav.Header logo={<IconSemiLogo style={{ height: '36px', fontSize: 36 }} />} text={'Semi 运营后台'} />
                <Nav.Item itemKey={'union'} text={'活动管理'} icon={<IconStar />} />
                <Nav.Sub itemKey={'user'} text="Semi组件展示" icon={<IconUser />}>
                  <Nav.Item itemKey={'grids'} text={'网格'} />
                  <Nav.Item itemKey={'forms'} text={'表单'} />

                  <Nav.Item itemKey={'negative'} text={'非活跃用户'} />
                </Nav.Sub>
                <Nav.Sub itemKey={'union-management'} text="任务管理" icon={<IconUserGroup />}>
                  <Nav.Item itemKey={'notice'} text={'任务设置'} />
                  <Nav.Item itemKey={'query'} text={'任务查询'} />
                  <Nav.Item itemKey={'info'} text={'信息录入'} />
                </Nav.Sub>
                <Nav.Footer collapseButton={true} />
              </Nav>
            </Sider>
            <Layout>
              <Content
                style={{
                  padding: '24px',
                  backgroundColor: 'var(--semi-color-bg-0)',
                  height:'640px',
                  overflow:'auto',
                }}
              >
                <Breadcrumb
                  style={{
                    marginBottom: '24px',
                  }}
                  routes={['首页', '当这个页面标题很长时需要省略', '上一页', '详情页']}
                />
                <div
                  style={{
                    borderRadius: '10px',
                    border: '1px solid var(--semi-color-border)',
                    minHeight: '376px',
                    padding: '32px',
                  }}
                >
                  {children}
                </div>

              </Content>
              <Footer
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  padding: '20px',
                  color: 'var(--semi-color-text-2)',
                  backgroundColor: 'rgba(var(--semi-grey-0), 1)',
                }}
              >
                <span
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                  }}
                >
                  <IconBytedanceLogo size="large" style={{ marginRight: '8px' }} />
                  <span>Copyright © 2023 ByteDance. All Rights Reserved. </span>
                </span>
                <span>
                  <span style={{ marginRight: '24px' }}>平台客服</span>
                  <span>反馈建议</span>
                </span>
              </Footer>
            </Layout>

          </Layout>


        </Layout>
      </body>
    </html>
  )
}



